import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1785441538799 implements MigrationInterface {
    name = 'Migration1785441538799'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`campaign_posts\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`candidacy_id\` varchar(255) NOT NULL, \`title\` varchar(255) NOT NULL, \`content\` text NOT NULL, \`media_url\` varchar(255) NULL, \`published_at\` timestamp NULL, \`code\` varchar(255) NULL, INDEX \`IDX_3f219fc54c8cce2e7cb48d57d9\` (\`candidacy_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`candidacies\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`user_id\` varchar(255) NOT NULL, \`election_id\` varchar(255) NOT NULL, \`position\` varchar(255) NOT NULL, \`photo_url\` varchar(255) NULL, \`reviewed_by_id\` varchar(255) NULL, \`approved_at\` timestamp NULL, \`rejected_at\` timestamp NULL, \`code\` varchar(255) NULL, INDEX \`IDX_ac2b1ea47ffa3379f5f998c95d\` (\`user_id\`), INDEX \`IDX_d97bcd0e8c219ed123c73aaa41\` (\`election_id\`), UNIQUE INDEX \`uq_candidacy_user_election\` (\`user_id\`, \`election_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`candidacy_programs\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`candidacy_id\` varchar(255) NOT NULL, \`content\` text NOT NULL, \`code\` varchar(255) NULL, UNIQUE INDEX \`IDX_3c8f3513674fdf6ce006b0aa03\` (\`candidacy_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`conditions\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`election_id\` varchar(255) NOT NULL, \`type\` enum ('candidate', 'voter', 'campaign') NOT NULL, \`title\` varchar(255) NOT NULL, \`description\` text NULL, \`is_mandatory\` tinyint NOT NULL DEFAULT 1, \`is_active\` tinyint NOT NULL DEFAULT 1, \`position\` int NOT NULL DEFAULT '0', \`code\` varchar(255) NULL, INDEX \`IDX_baae627ac8c02014636a45a850\` (\`election_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`elections\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`jurisdiction_id\` varchar(255) NOT NULL, \`year\` int NOT NULL, \`title\` varchar(255) NOT NULL, \`description\` text NULL, \`status\` enum ('draft', 'active', 'closed') NOT NULL DEFAULT 'draft', \`starts_at\` timestamp NULL, \`ends_at\` timestamp NULL, \`results_published\` tinyint NOT NULL DEFAULT 0, \`code\` varchar(255) NULL, INDEX \`IDX_525353c003cfee309c60203ab1\` (\`jurisdiction_id\`), UNIQUE INDEX \`uq_election_year_jurisdiction\` (\`year\`, \`jurisdiction_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`electoral_rolls\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`user_id\` varchar(255) NOT NULL, \`election_id\` varchar(255) NOT NULL, \`registered_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, \`code\` varchar(255) NULL, INDEX \`IDX_2109c408088bcef5875143c5b2\` (\`user_id\`), INDEX \`IDX_9bb675b88f2c68dd76066a633b\` (\`election_id\`), UNIQUE INDEX \`uq_roll_user_election\` (\`user_id\`, \`election_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`jurisdictions\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`name\` varchar(255) NOT NULL, \`type\` enum ('federation', 'state') NOT NULL, \`parent_id\` varchar(255) NULL, \`code\` varchar(255) NULL, INDEX \`IDX_c9013be826e2dda9833786caa8\` (\`parent_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`votes\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`election_id\` varchar(255) NOT NULL, \`candidacy_id\` varchar(255) NOT NULL, \`user_id\` varchar(255) NOT NULL, \`receipt_code\` varchar(255) NOT NULL, \`code\` varchar(255) NULL, INDEX \`IDX_4ad69daaa81656c07c10d833dc\` (\`election_id\`), INDEX \`IDX_eb2036496721258014effec2e2\` (\`candidacy_id\`), INDEX \`IDX_27be2cab62274f6876ad6a3164\` (\`user_id\`), UNIQUE INDEX \`IDX_e103f79fe8f22cde57167a2704\` (\`receipt_code\`), UNIQUE INDEX \`uq_vote_user_election\` (\`user_id\`, \`election_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`mail_failed_jobs\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`type\` enum ('confirm-email', 'reset-password', 'reset-pin', 'reset-link') NOT NULL, \`to\` varchar(255) NOT NULL, \`payload\` json NOT NULL, \`last_error\` text NULL, \`attempts\` int NOT NULL DEFAULT '0', \`status\` enum ('pending', 'abandoned') NOT NULL DEFAULT 'pending', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`achievements\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`candidacy_id\` varchar(255) NOT NULL, \`category_id\` varchar(255) NOT NULL, \`title\` varchar(255) NOT NULL, \`description\` text NULL, \`proof_url\` varchar(255) NULL, \`proof_snapshot\` text NULL, \`reviewed_by_id\` varchar(255) NULL, \`approved_at\` timestamp NULL, \`rejected_at\` timestamp NULL, \`code\` varchar(255) NULL, INDEX \`IDX_66402a7d0dcc4e1d6a9f276a92\` (\`candidacy_id\`), INDEX \`IDX_83bf9cfb0ea2c1ac752d696607\` (\`category_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`action_categories\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`label\` varchar(255) NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`code\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`audit_logs\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`actor_id\` varchar(255) NOT NULL, \`action\` varchar(255) NOT NULL, \`entity_type\` varchar(255) NOT NULL, \`entity_id\` varchar(255) NOT NULL, \`details\` text NULL, INDEX \`IDX_177183f29f438c488b5e8510cd\` (\`actor_id\`), INDEX \`IDX_ea9ba3dfb39050f831ee3be40d\` (\`entity_type\`), INDEX \`IDX_85c204d8e47769ac183b32bf9c\` (\`entity_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`contestations\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`achievement_id\` varchar(255) NOT NULL, \`reporter_id\` varchar(255) NOT NULL, \`reason\` text NOT NULL, \`resolved_by_id\` varchar(255) NULL, \`resolved_at\` timestamp NULL, \`code\` varchar(255) NULL, INDEX \`IDX_fc715beeb8f40e858fde42b284\` (\`achievement_id\`), INDEX \`IDX_a70706cafd825b24c43227cb4d\` (\`reporter_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`questions\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`candidacy_id\` varchar(255) NOT NULL, \`author_id\` varchar(255) NOT NULL, \`content\` text NOT NULL, \`answer\` text NULL, \`answered_at\` timestamp NULL, \`hidden_at\` timestamp NULL, \`code\` varchar(255) NULL, INDEX \`IDX_e9c0594b99a415efc733ef9f62\` (\`candidacy_id\`), INDEX \`IDX_dcaac7adf4b5af7bc980ec5250\` (\`author_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`first_name\` varchar(255) NULL, \`last_name\` varchar(255) NULL, \`email\` varchar(255) NULL, \`phone\` varchar(255) NULL, \`img_prof\` varchar(255) NULL, \`jurisdiction_id\` varchar(255) NULL, \`password\` varchar(255) NULL, \`google_id\` varchar(255) NULL, \`pin_code\` text NULL, \`status\` enum ('active', 'unverified', 'disabled', 'blocked', 'deleted') NOT NULL DEFAULT 'unverified', \`roles\` set ('voter', 'candidate', 'admin', 'commission') NOT NULL DEFAULT 'voter', \`code\` varchar(255) NOT NULL, \`id_country\` varchar(255) NULL, UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), UNIQUE INDEX \`IDX_0bd5012aeb82628e07f6a1be53\` (\`google_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_devices\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`user_id\` varchar(255) NOT NULL, \`device_fingerprint\` varchar(64) NOT NULL, \`device_name\` varchar(255) NULL, \`device_type\` enum ('mobile', 'desktop', 'tablet', 'unknown') NULL DEFAULT 'unknown', \`os\` varchar(255) NULL, \`browser\` varchar(255) NULL, \`fcm_token\` text NULL, \`last_active_at\` datetime NULL, INDEX \`IDX_28bd79e1b3f7c1168f0904ce24\` (\`user_id\`), UNIQUE INDEX \`IDX_f75ac6098cb66552fd9a389157\` (\`device_fingerprint\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_sessions\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`user_id\` varchar(255) NOT NULL, \`device_fingerprint\` varchar(64) NOT NULL, \`refresh_token_hash\` varchar(64) NOT NULL, \`expires_at\` datetime NOT NULL, \`last_active_at\` datetime NOT NULL, \`ip\` varchar(45) NULL, INDEX \`IDX_e9658e959c490b0a634dfc5478\` (\`user_id\`), UNIQUE INDEX \`IDX_cc132fa5f7a96610010e293e52\` (\`refresh_token_hash\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`user_devices\` ADD CONSTRAINT \`FK_28bd79e1b3f7c1168f0904ce241\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_sessions\` ADD CONSTRAINT \`FK_e9658e959c490b0a634dfc54783\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_sessions\` ADD CONSTRAINT \`FK_f2b45e7d39891a95f44bb89f4ea\` FOREIGN KEY (\`device_fingerprint\`) REFERENCES \`user_devices\`(\`device_fingerprint\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`user_sessions\` DROP FOREIGN KEY \`FK_f2b45e7d39891a95f44bb89f4ea\``);
        await queryRunner.query(`ALTER TABLE \`user_sessions\` DROP FOREIGN KEY \`FK_e9658e959c490b0a634dfc54783\``);
        await queryRunner.query(`ALTER TABLE \`user_devices\` DROP FOREIGN KEY \`FK_28bd79e1b3f7c1168f0904ce241\``);
        await queryRunner.query(`DROP INDEX \`IDX_cc132fa5f7a96610010e293e52\` ON \`user_sessions\``);
        await queryRunner.query(`DROP INDEX \`IDX_e9658e959c490b0a634dfc5478\` ON \`user_sessions\``);
        await queryRunner.query(`DROP TABLE \`user_sessions\``);
        await queryRunner.query(`DROP INDEX \`IDX_f75ac6098cb66552fd9a389157\` ON \`user_devices\``);
        await queryRunner.query(`DROP INDEX \`IDX_28bd79e1b3f7c1168f0904ce24\` ON \`user_devices\``);
        await queryRunner.query(`DROP TABLE \`user_devices\``);
        await queryRunner.query(`DROP INDEX \`IDX_0bd5012aeb82628e07f6a1be53\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_dcaac7adf4b5af7bc980ec5250\` ON \`questions\``);
        await queryRunner.query(`DROP INDEX \`IDX_e9c0594b99a415efc733ef9f62\` ON \`questions\``);
        await queryRunner.query(`DROP TABLE \`questions\``);
        await queryRunner.query(`DROP INDEX \`IDX_a70706cafd825b24c43227cb4d\` ON \`contestations\``);
        await queryRunner.query(`DROP INDEX \`IDX_fc715beeb8f40e858fde42b284\` ON \`contestations\``);
        await queryRunner.query(`DROP TABLE \`contestations\``);
        await queryRunner.query(`DROP INDEX \`IDX_85c204d8e47769ac183b32bf9c\` ON \`audit_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_ea9ba3dfb39050f831ee3be40d\` ON \`audit_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_177183f29f438c488b5e8510cd\` ON \`audit_logs\``);
        await queryRunner.query(`DROP TABLE \`audit_logs\``);
        await queryRunner.query(`DROP TABLE \`action_categories\``);
        await queryRunner.query(`DROP INDEX \`IDX_83bf9cfb0ea2c1ac752d696607\` ON \`achievements\``);
        await queryRunner.query(`DROP INDEX \`IDX_66402a7d0dcc4e1d6a9f276a92\` ON \`achievements\``);
        await queryRunner.query(`DROP TABLE \`achievements\``);
        await queryRunner.query(`DROP TABLE \`mail_failed_jobs\``);
        await queryRunner.query(`DROP INDEX \`uq_vote_user_election\` ON \`votes\``);
        await queryRunner.query(`DROP INDEX \`IDX_e103f79fe8f22cde57167a2704\` ON \`votes\``);
        await queryRunner.query(`DROP INDEX \`IDX_27be2cab62274f6876ad6a3164\` ON \`votes\``);
        await queryRunner.query(`DROP INDEX \`IDX_eb2036496721258014effec2e2\` ON \`votes\``);
        await queryRunner.query(`DROP INDEX \`IDX_4ad69daaa81656c07c10d833dc\` ON \`votes\``);
        await queryRunner.query(`DROP TABLE \`votes\``);
        await queryRunner.query(`DROP INDEX \`IDX_c9013be826e2dda9833786caa8\` ON \`jurisdictions\``);
        await queryRunner.query(`DROP TABLE \`jurisdictions\``);
        await queryRunner.query(`DROP INDEX \`uq_roll_user_election\` ON \`electoral_rolls\``);
        await queryRunner.query(`DROP INDEX \`IDX_9bb675b88f2c68dd76066a633b\` ON \`electoral_rolls\``);
        await queryRunner.query(`DROP INDEX \`IDX_2109c408088bcef5875143c5b2\` ON \`electoral_rolls\``);
        await queryRunner.query(`DROP TABLE \`electoral_rolls\``);
        await queryRunner.query(`DROP INDEX \`uq_election_year_jurisdiction\` ON \`elections\``);
        await queryRunner.query(`DROP INDEX \`IDX_525353c003cfee309c60203ab1\` ON \`elections\``);
        await queryRunner.query(`DROP TABLE \`elections\``);
        await queryRunner.query(`DROP INDEX \`IDX_baae627ac8c02014636a45a850\` ON \`conditions\``);
        await queryRunner.query(`DROP TABLE \`conditions\``);
        await queryRunner.query(`DROP INDEX \`IDX_3c8f3513674fdf6ce006b0aa03\` ON \`candidacy_programs\``);
        await queryRunner.query(`DROP TABLE \`candidacy_programs\``);
        await queryRunner.query(`DROP INDEX \`uq_candidacy_user_election\` ON \`candidacies\``);
        await queryRunner.query(`DROP INDEX \`IDX_d97bcd0e8c219ed123c73aaa41\` ON \`candidacies\``);
        await queryRunner.query(`DROP INDEX \`IDX_ac2b1ea47ffa3379f5f998c95d\` ON \`candidacies\``);
        await queryRunner.query(`DROP TABLE \`candidacies\``);
        await queryRunner.query(`DROP INDEX \`IDX_3f219fc54c8cce2e7cb48d57d9\` ON \`campaign_posts\``);
        await queryRunner.query(`DROP TABLE \`campaign_posts\``);
    }

}
